begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into app.actors(id,workos_user_id,primary_email,display_name,email_verified) values
 ('b6000000-0000-4000-8000-000000000001','user_feedback_one','one@fixture.example','Fixture One',true),
 ('b6000000-0000-4000-8000-000000000002','user_feedback_two','two@fixture.example','Fixture Two',true),
 ('b6000000-0000-4000-8000-000000000003','user_feedback_unverified','unverified@fixture.example','Unverified',false),
 ('b6000000-0000-4000-8000-000000000004','user_feedback_reviewer','chussey@aia4.io','Fixture Reviewer',true);
insert into app.operator_grants(actor_id,allowlisted_email,permissions,status,approved_by,approved_at,workos_organization_id) values
 ('b6000000-0000-4000-8000-000000000004','chussey@aia4.io',array['listing_review'],'active','local-fixture',statement_timestamp(),'org_feedback_fixture');
create temp table feedback_receipt(id uuid);
grant all on feedback_receipt to authenticated;
create temp table feedback_baseline as select count(*) as outbox from app.integration_outbox;
select extensions.ok((select relrowsecurity from pg_class where oid='private.directory_feedback'::regclass),'feedback table has RLS');
select extensions.ok(not has_table_privilege('anon','private.directory_feedback','select'),'anonymous cannot read private feedback');
select extensions.ok(not has_table_privilege('authenticated','private.directory_feedback','select'),'other authenticated users cannot read private feedback');
select extensions.ok(not has_table_privilege('service_role','private.feedback_linear_outbox','select'),'live service role cannot dispatch held Linear queue');
select extensions.ok(not has_function_privilege('anon','public.submit_directory_feedback(jsonb,text)','execute'),'anonymous cannot submit');
select extensions.ok(not has_function_privilege('authenticated','private.feedback_review_allowed()','execute'),'authorization helper is not exposed');
set local role authenticated;
select set_config('request.jwt.claims','{}',true);
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":true}','feedback-fixture-one')$$,'P0001','authentication_required','missing identity denied');
select set_config('request.jwt.claims','{"sub":"user_feedback_unverified"}',true);
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":true}','feedback-fixture-one')$$,'P0001','verified_identity_required','unverified identity denied');
select set_config('request.jwt.claims','{"sub":"user_feedback_one"}',true);
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":false}','feedback-fixture-one')$$,'P0001','invalid_feedback','consent required');
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":true,"email":"private@example.test"}','feedback-fixture-one')$$,'P0001','invalid_feedback','contact and extra fields rejected');
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":true}','bad')$$,'P0001','invalid_feedback','invalid retry key rejected');
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"security","title":"Fixture bug","details":"Synthetic detailed bug report.","consent":true}','feedback-fixture-one')$$,'P0001','invalid_feedback','unsupported type rejected');
insert into feedback_receipt select (public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.\nWith steps to reproduce.","consent":true}','feedback-fixture-one')->>'id')::uuid;
select extensions.is((public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.\nWith steps to reproduce.","consent":true}','feedback-fixture-one')->>'id')::uuid,(select id from feedback_receipt),'uncertain retry returns identical receipt');
select extensions.is((public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.\nWith steps to reproduce.","consent":true}','feedback-fixture-alias')->>'id')::uuid,(select id from feedback_receipt),'same user content deduplicates across new key');
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"feature","title":"Changed title","details":"Synthetic changed feedback report.","consent":true}','feedback-fixture-alias')$$,'P0001','idempotency_conflict','duplicate alias cannot be replayed with changed body');
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','ordinary user cannot view moderation queue');
select set_config('request.jwt.claims','{"sub":"user_feedback_two"}',true);
select extensions.is((public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.\nWith steps to reproduce.","consent":true}','feedback-fixture-one')->>'duplicate')::boolean,false,'other user same text and key creates isolated receipt');
select extensions.throws_ok(format('select public.decide_directory_feedback(%L::uuid,%L,%L,null,null)',(select id from feedback_receipt),'dismissed','Fixture decision'),'P0001','feedback_review_forbidden','other user cannot decide a submission');
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','org_feedback_fixture','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','listing_review does not grant feedback review');
reset role;
update app.operator_grants set permissions=array['feedback_review'] where actor_id='b6000000-0000-4000-8000-000000000004';
set local role authenticated;
select extensions.is(jsonb_array_length(public.review_directory_feedback()),2,'explicitly scoped reviewer sees two pending submissions');
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','wrong_org','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','wrong organization denied');
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','org_feedback_fixture','auth_time',extract(epoch from statement_timestamp())::bigint-901)::text,true);
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','expired recent authentication denied');
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','org_feedback_fixture','auth_time',extract(epoch from statement_timestamp())::bigint,'impersonator_id','fixture')::text,true);
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','impersonation denied');
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','org_feedback_fixture','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
select extensions.throws_ok(format('select public.decide_directory_feedback(%L::uuid,%L,%L,null,null)',(select id from feedback_receipt),'approved','Fixture decision'),'P0001','invalid_feedback_decision','sanitized triage copy required');
select extensions.is(public.decide_directory_feedback((select id from feedback_receipt),'approved','Reviewed synthetic content','Sanitized fixture issue','Sanitized reproduction steps for the directory team.')->>'delivery','held','approval prepares held queue only');
select extensions.is((public.decide_directory_feedback((select id from feedback_receipt),'approved','Reviewed synthetic content','Sanitized fixture issue','Sanitized reproduction steps for the directory team.')->>'idempotent')::boolean,true,'repeated decision is idempotent');
select extensions.throws_ok(format('select public.decide_directory_feedback(%L::uuid,%L,%L,null,null)',(select id from feedback_receipt),'dismissed','Different decision'),'P0001','idempotency_conflict','conflicting decision denied');
reset role;
select extensions.is((select count(*) from private.feedback_linear_outbox),1::bigint,'only one held delivery record exists');
select extensions.is((select status from private.feedback_linear_outbox),'held','nothing is activated');
select extensions.is((select team_id from private.feedback_linear_outbox),'f81dd6ad-8f9f-4d94-b59a-2b72cb995386','fixed 775Local destination');
select extensions.is((select details from private.feedback_linear_outbox),'Sanitized reproduction steps for the directory team.','only separately reviewed text enters delivery queue');
select extensions.is((select count(*) from app.integration_outbox),(select outbox from feedback_baseline),'GHL delivery queue unchanged');
select extensions.is((select count(*) from app.audit_events where action='feedback.moderated'),1::bigint,'one minimal moderation audit receipt');
select extensions.ok(not exists(select 1 from app.audit_events where action like 'feedback.%' and (coalesce(after_ref::text,'')||coalesce(before_ref::text,'')) ilike '%Synthetic detailed%'),'raw report never enters audit payload');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"user_feedback_one"}',true);
select public.submit_directory_feedback(jsonb_build_object('kind','feature','title','Fixture request '||n,'details','Synthetic feature request details '||n,'consent',true),'feedback-rate-'||n) from generate_series(1,3)n;
select extensions.throws_ok($$select public.submit_directory_feedback('{"kind":"feature","title":"Over budget","details":"Synthetic over-budget feedback details.","consent":true}','feedback-rate-over')$$,'P0001','feedback_rate_limited','sixth unique submission receipt within hour is rate limited');
select extensions.is((public.submit_directory_feedback('{"kind":"bug","title":"Fixture bug","details":"Synthetic detailed bug report.\nWith steps to reproduce.","consent":true}','feedback-fixture-one')->>'id')::uuid,(select id from feedback_receipt),'exact uncertain retry remains available at rate limit');
reset role;
update app.operator_grants set status='revoked',approved_at=null,revoked_at=statement_timestamp() where actor_id='b6000000-0000-4000-8000-000000000004';
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub','user_feedback_reviewer','org_id','org_feedback_fixture','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
select extensions.throws_ok($$select public.review_directory_feedback()$$,'P0001','feedback_review_forbidden','revoked operator denied');
reset role;
select * from extensions.finish();
rollback;
