begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into app.actors(id,workos_user_id,primary_email) values
 ('91000000-0000-4000-8000-000000000001','authority_owner','owner@shop.example'),
 ('91000000-0000-4000-8000-000000000002','authority_manager','manager@shop.example'),
 ('91000000-0000-4000-8000-000000000003','authority_other','other@gmail.com'),
 ('91000000-0000-4000-8000-000000000004','authority_operator','chussey@aia4.io');
insert into app.operator_grants(actor_id,allowlisted_email,permissions,status,approved_at,workos_organization_id) values('91000000-0000-4000-8000-000000000004','chussey@aia4.io',array['claim_review'],'active',statement_timestamp(),'org_test');
insert into app.businesses(id,canonical_name) values('92000000-0000-4000-8000-000000000001','Synthetic Shop');
insert into app.business_listings(id,business_id,current_slug,display_name,website_url,city_slug,postal_code,publication_status,published_at) values
 ('93000000-0000-4000-8000-000000000001','92000000-0000-4000-8000-000000000001','synthetic-shop','Synthetic Shop','https://shop.example','reno','89502','published',statement_timestamp()),
 ('93000000-0000-4000-8000-000000000002','92000000-0000-4000-8000-000000000001','wrong-city','Wrong City','https://shop.example','sparks','89431','published',statement_timestamp());
select set_config('request.jwt.claims','{"sub":"authority_manager"}',true);
set local role authenticated;
select extensions.throws_ok($$select public.submit_listing_claim('93000000-0000-4000-8000-000000000002','document','wrong-city-key','listing_manager')$$,'P0001','listing is not claimable','wrong location is rejected');
select extensions.throws_ok($$select public.submit_listing_claim('93000000-0000-4000-8000-000000000001','document','wrong-role-key','operator')$$,'P0001','invalid claim command','role cannot become operator');
select extensions.is(public.submit_listing_claim('93000000-0000-4000-8000-000000000001','business_domain','manager-submit-key','listing_manager')->>'status','needs_evidence','domain hint alone needs independent evidence');
select extensions.is(public.submit_listing_claim('93000000-0000-4000-8000-000000000001','business_domain','manager-submit-key','listing_manager')->>'owner_authority','false','duplicate click grants no authority');
select extensions.throws_ok($$select public.submit_listing_claim('93000000-0000-4000-8000-000000000001','document','manager-submit-key','business_owner')$$,'P0001','idempotency_conflict','key cannot change scope');
select extensions.throws_ok($$select public.submit_listing_claim('93000000-0000-4000-8000-000000000001','document','manager-other-key','business_owner')$$,'P0001','open_claim_conflict','open claim cannot change role');
reset role;
create temporary table fixture as select id claim_id,evidence_challenge challenge from app.claims where submission_idempotency_key='manager-submit-key';
grant select on fixture to authenticated;
set local role authenticated;
select extensions.throws_ok($$select public.submit_claim_evidence((select claim_id from fixture),'99000000-0000-4000-8000-000000000001','Nevada registry entry 123','I manage this exact Reno service location.','evidence-test-key')$$,'P0001','challenge_expired_or_replayed','wrong challenge rejected');
select extensions.is(public.submit_claim_evidence((select claim_id from fixture),(select challenge from fixture),'Nevada registry entry 123','I manage this exact Reno service location.','evidence-test-key')->>'status','submitted','evidence saved privately for investigation');
select extensions.is(public.submit_claim_evidence((select claim_id from fixture),(select challenge from fixture),'Nevada registry entry 123','I manage this exact Reno service location.','evidence-test-key')->>'idempotent','true','interrupted evidence retry is idempotent');
select extensions.throws_ok($$select public.submit_claim_evidence((select claim_id from fixture),(select challenge from fixture),'Nevada registry entry 123','I manage this exact Reno service location.','evidence-test-replay')$$,'P0001','challenge_expired_or_replayed','used challenge cannot replay with new key');
reset role;
select extensions.ok(not has_table_privilege('authenticated','private.claim_evidence','select'),'private proof table is not readable');
select extensions.ok(not has_table_privilege('anon','private.claim_evidence','select'),'anonymous cannot read evidence');
set local role authenticated;
select extensions.throws_ok($$select public.get_claim_review_evidence((select claim_id from fixture))$$,'P0001','reauth_required','claimant cannot read operator proof');
reset role;
select set_config('request.jwt.claims','{"sub":"authority_other"}',true);
set local role authenticated;
select extensions.is(public.get_my_listing_claim('93000000-0000-4000-8000-000000000001'),null::jsonb,'other user cannot see claimant status');
select extensions.throws_ok($$select public.submit_claim_evidence((select claim_id from fixture),(select challenge from fixture),'Nevada registry entry 123','I manage this exact Reno service location.','other-evidence-key')$$,'P0001','claim_access_forbidden','other user cannot attach proof');
select extensions.throws_ok($$select public.withdraw_listing_claim((select claim_id from fixture))$$,'P0001','claim_access_forbidden','other user cannot withdraw');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','authority_operator','org_id','org_test','auth_time',extract(epoch from statement_timestamp())::bigint-1000)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.get_claim_review_evidence((select claim_id from fixture))$$,'P0001','reauth_required','stale reviewer cannot read proof');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','authority_operator','org_id','org_test','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.decide_listing_claim((select claim_id from fixture),'approved','A work domain match alone','manager-decision-key')$$,'P0001','independent_authority_review_required','domain-only approval blocked');
select extensions.ok((public.get_claim_review_evidence((select claim_id from fixture))->'evidence'->0->>'reference')='Nevada registry entry 123','recent authorized operator reads private evidence');
select extensions.throws_ok($$select public.review_claim_authority((select claim_id from fixture),(public.get_claim_review_evidence((select claim_id from fixture))->'evidence'->0->>'id')::uuid,'Identity confirmed independently','Manager authorization confirmed independently','No conflicting participants',statement_timestamp()+interval '7 days','{}')$$,'P0001','claim_scope_changed','assessment cannot bind wrong listing snapshot');
select extensions.is(public.review_claim_authority((select claim_id from fixture),(public.get_claim_review_evidence((select claim_id from fixture))->'evidence'->0->>'id')::uuid,'Identity confirmed independently','Manager authorization confirmed independently','No conflicting participants',statement_timestamp()+interval '7 days',public.get_claim_review_evidence((select claim_id from fixture))->'scope')->>'status','human_reviewed','independent scoped assessment recorded');
reset role;
select set_config('request.jwt.claims','{"sub":"authority_owner"}',true);
set local role authenticated;
select extensions.is(public.submit_listing_claim('93000000-0000-4000-8000-000000000001','document','owner-conflict-key','business_owner')->>'status','needs_evidence','competing owner claim enters exception queue');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','authority_operator','org_id','org_test','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.decide_listing_claim((select claim_id from fixture),'approved','Independent manager proof','manager-decision-key')$$,'P0001','independent_authority_review_required','concurrent competing claim invalidates earlier assessment');
select extensions.is(public.review_claim_authority((select claim_id from fixture),(public.get_claim_review_evidence((select claim_id from fixture))->'evidence'->0->>'id')::uuid,'Identity confirmed independently','Manager delegation verified with actual owner','Competing claimant independently contacted; manager delegation confirmed',statement_timestamp()+interval '7 days',public.get_claim_review_evidence((select claim_id from fixture))->'scope')->>'status','human_reviewed','human resolves current conflict snapshot');
select extensions.is(public.decide_listing_claim((select claim_id from fixture),'approved','Independent manager proof','manager-decision-key')->>'status','approved','reviewed manager receives manager participation');
select extensions.is(public.decide_listing_claim((select claim_id from fixture),'approved','Independent manager proof','manager-decision-key')->>'idempotent','true','decision replay creates no second grant');
reset role;
select extensions.is((select role from app.listing_participations where claim_id=(select claim_id from fixture)),'listing_manager','manager approval never becomes owner');
select extensions.is((select authority_scope->>'participants' from app.listing_participations where claim_id=(select claim_id from fixture)),'none','manager cannot delegate authority');
select extensions.ok((select not authority_scope?'leads' from app.listing_participations where claim_id=(select claim_id from fixture)),'claim approval does not grant lead delivery');
select extensions.ok((select owner_verified_at is null from app.business_listings where id='93000000-0000-4000-8000-000000000001'),'manager approval does not create owner label');
select extensions.is((select count(*)::integer from app.listing_participations where claim_id=(select claim_id from fixture)),1,'exactly one participation after replay');
select set_config('request.jwt.claims','{"sub":"authority_manager"}',true);
set local role authenticated;
select extensions.is(public.get_my_listing_claim('93000000-0000-4000-8000-000000000001')->>'role','listing_manager','manager sees current role');
select extensions.is(public.get_my_listing_claim('93000000-0000-4000-8000-000000000001')->>'owner_authority','false','manager sees no owner authority');
reset role;
update app.listing_participations set expires_at=statement_timestamp()-interval '1 second',starts_at=statement_timestamp()-interval '1 day' where claim_id=(select claim_id from fixture);
set local role authenticated;
select extensions.is(public.get_my_listing_claim('93000000-0000-4000-8000-000000000001')->>'authority_active','false','expired approval reports no active authority');
select extensions.throws_ok($$select public.pilot_workspace('93000000-0000-4000-8000-000000000001')$$,'P0001','listing_access_forbidden','expired participation loses studio');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','authority_operator','org_id','org_test','auth_time',extract(epoch from statement_timestamp())::bigint)::text,true);
set local role authenticated;
select extensions.is(public.revoke_listing_authority((select id from app.listing_participations where claim_id=(select claim_id from fixture)),'Delegation withdrawn by owner')->>'status','revoked','operator can revoke with reason');
select extensions.is(public.revoke_listing_authority((select id from app.listing_participations where claim_id=(select claim_id from fixture)),'Delegation withdrawn by owner')->>'idempotent','true','revoke replay is harmless');
reset role;
select extensions.is((select count(*)::integer from app.audit_events where action='listing_participation.revoked' and target_id=(select id::text from app.listing_participations where claim_id=(select claim_id from fixture))),1,'revocation audited once');
select set_config('request.jwt.claims','{"sub":"authority_owner"}',true);
set local role authenticated;
select extensions.is(public.withdraw_listing_claim((select id from app.claims where submission_idempotency_key='owner-conflict-key'))->>'status','withdrawn','own pending claim can be withdrawn');
select extensions.is(public.withdraw_listing_claim((select id from app.claims where submission_idempotency_key='owner-conflict-key'))->>'idempotent','true','withdraw replay is harmless');
select * from extensions.finish();
rollback;
