begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into app.actors(id,workos_user_id,primary_email) values
('d1000000-0000-4000-8000-000000000001','publication_requester','owner@fixture.example'),
('d1000000-0000-4000-8000-000000000002','publication_other','other@fixture.example'),
('d1000000-0000-4000-8000-000000000003','publication_operator','chussey@aia4.io');
insert into app.operator_grants(actor_id,allowlisted_email,permissions,status,approved_at,workos_organization_id) values('d1000000-0000-4000-8000-000000000003','chussey@aia4.io',array['listing_review','listing_publish'],'active',statement_timestamp(),'org_publication');
insert into app.categories(slug,name) values('publication-fixture','Publication Fixture');
create temporary table f(id uuid,scope jsonb,payload jsonb,decision jsonb,listing_id uuid);
grant all on f to authenticated;
select set_config('request.jwt.claims','{"sub":"publication_requester"}',true);
set local role authenticated;
insert into f(payload) values('{"name":"Synthetic New Shop","citySlug":"reno","categorySlug":"publication-fixture","phone":"+17755550101","zip":"89502","description":"Synthetic home repair service.","website":"https://publication.example"}');
update f set id=(public.request_business_listing(payload,'publication-request-key')->>'id')::uuid;
select extensions.is(jsonb_array_length(public.get_my_listing_requests()),1,'requester sees own receipt');
select extensions.throws_ok($$select public.get_listing_request_review((select id from f))$$,'P0001','reauth_required','claimant cannot access review command');
reset role;
select set_config('request.jwt.claims','{"sub":"publication_other"}',true);
set local role authenticated;
select extensions.is(jsonb_array_length(public.get_my_listing_requests()),0,'other user sees no request');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint-1000)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.get_listing_request_review((select id from f))$$,'P0001','reauth_required','stale reviewer blocked');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
update f set scope=public.get_listing_request_review(id)->'scope',decision=jsonb_build_object('outcome','approved','reason','Independent synthetic identity/source checks complete.','sourceUrls',jsonb_build_array('https://publication.example'),'sourceCheckedAt',statement_timestamp(),'checks','{"nap":true,"activeBusiness":true,"category":true,"reno":true,"rights":true,"privacy":true,"duplicates":true}'::jsonb,'duplicateDecision','no_duplicate','canonical',payload);
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision||'{"checks":{}}' from f),(select scope from f),'publication-no-checks')$$,'P0001','publication_checks_required','all deterministic publication checks required');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision||'{"sourceUrls":[]}' from f),(select scope from f),'publication-no-sources')$$,'P0001','publication_sources_required','verified source receipt required');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select jsonb_set(decision,'{canonical,citySlug}','"sparks"') from f),(select scope from f),'publication-wrong-city')$$,'P0001','invalid_listing_review','Reno pilot enforced at database boundary');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select jsonb_set(decision,'{canonical,street}','"private home"') from f),(select scope from f),'publication-private-street')$$,'P0001','invalid_listing_review','street/private field cannot publish');
select extensions.is(public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-decision-key')->>'status','approved','manually reviewed request publishes');
select extensions.is(public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-decision-key')->>'idempotent','true','retry returns original receipt');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision||'{"reason":"Changed private operator reason"}' from f),(select scope from f),'publication-decision-key')$$,'P0001','idempotency_conflict','key cannot change approved decision');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-another-key')$$,'P0001','request_already_decided','terminal decision cannot create second listing');
reset role;
update f set listing_id=(select listing_id from app.listing_requests where id=f.id);
select extensions.is((select count(*)::integer from app.listing_request_receipts where request_id=(select id from f)),1,'immutable reviewed receipt retained');
select extensions.is((select count(*)::integer from app.listing_revisions where listing_id=(select listing_id from app.listing_requests where id=(select id from f))),1,'reversible canonical creation revision retained');
select extensions.is((select count(*)::integer from public.directory_listings where id=(select listing_id from app.listing_requests where id=(select id from f))),1,'reviewed request visible through public projection');
select extensions.ok((select is_service_area and hide_street and street_address is null and owner_verified_at is null from app.business_listings where id=(select listing_id from app.listing_requests where id=(select id from f))),'residential privacy preserved; no ownership label');
select extensions.is((select count(*)::integer from app.listing_participations where actor_id='d1000000-0000-4000-8000-000000000001'),0,'publication creates no business authority');
select extensions.ok(not has_table_privilege('authenticated','app.listing_request_receipts','update'),'review receipts cannot be edited');
select set_config('request.jwt.claims','{"sub":"publication_requester"}',true);
set local role authenticated;
select extensions.is(public.get_my_listing_requests()->0->>'status','approved','requester receives truthful approved status');
select extensions.ok(length(public.get_my_listing_requests()->0->>'slug')>0,'requester receives public listing link, not studio grant');
update f set id=(public.request_business_listing(payload||'{"name":"Different Submitted Name"}','publication-duplicate-request')->>'id')::uuid;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
update f set scope=public.get_listing_request_review(id)->'scope';
select extensions.ok(jsonb_array_length((public.get_listing_request_review((select id from f)))->'duplicates')>0,'shared phone/website enters duplicate investigation');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-duplicate-key')$$,'P0001','duplicate_review_required','duplicate cannot be bypassed by attestation');
select extensions.is(public.decide_listing_request((select id from f),'{"outcome":"rejected","reason":"Existing location independently confirmed; use its listing."}',(select scope from f),'publication-reject-key')->>'status','rejected','operator can reject duplicate with durable reason');
reset role;
select extensions.is((select count(*)::integer from app.business_listings where current_slug like 'synthetic-new-shop-%'),1,'rejected request adds no listing');
-- Website alone must recognize conservative hostname aliases as potential duplicates.
select set_config('request.jwt.claims','{"sub":"publication_requester"}',true);
set local role authenticated;
update f set id=(public.request_business_listing(payload||'{"name":"Distinct Alias Shop","phone":"+17755550199","website":"https://www.publication.example.:443/"}','publication-alias-request')->>'id')::uuid;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
update f set scope=public.get_listing_request_review(id)->'scope';
select extensions.is(jsonb_array_length((public.get_listing_request_review((select id from f)))->'duplicates'),1,'www/default HTTPS port/trailing dot share duplicate identity');
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-alias-key')$$,'P0001','duplicate_review_required','website alias cannot create a public duplicate');
reset role;
-- Reviewed request publication can use existing audited rollback without manufacturing a launch receipt.
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.lives_ok($$select public.transition_listing_publication_state((select listing_id from f),'suspend',array['synthetic_correction'],'request-suspend-key')$$,'request publication has audited suspension');
reset role;
select extensions.is((select count(*)::integer from public.directory_listings where current_slug like 'synthetic-new-shop-%'),0,'suspended request disappears from public projection');
set local role authenticated;
select extensions.lives_ok($$select public.transition_listing_publication_state((select listing_id from f),'restore',array['synthetic_review_complete'],'request-restore-key')$$,'reviewed request restoration works');
reset role;
-- A concurrently changing duplicate invalidates the exact review snapshot.
select set_config('request.jwt.claims','{"sub":"publication_requester"}',true);
set local role authenticated;
update f set id=(public.request_business_listing(payload||'{"name":"Different Fresh Shop","phone":"+17755550102","website":"https://fresh.example"}','publication-fresh-request')->>'id')::uuid;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','publication_operator','org_id','org_publication','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
update f set scope=public.get_listing_request_review(id)->'scope';
reset role;
insert into app.businesses(id,canonical_name) values('d2000000-0000-4000-8000-000000000001','Concurrent Shop');
insert into app.business_listings(business_id,current_slug,display_name,phone_e164,city_slug,postal_code) values('d2000000-0000-4000-8000-000000000001','concurrent-request-shop','Concurrent Shop','+17755550102','reno','89502');
set local role authenticated;
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision from f),(select scope from f),'publication-stale-scope')$$,'P0001','listing_review_changed','concurrent conflicting listing invalidates review');
reset role;
update app.operator_grants set permissions=array['listing_review'] where actor_id='d1000000-0000-4000-8000-000000000003';
set local role authenticated;
select extensions.throws_ok($$select public.decide_listing_request((select id from f),(select decision from f),public.get_listing_request_review((select id from f))->'scope','publication-reviewer-only')$$,'P0001','publication_forbidden','review alone cannot publish');
reset role;
update app.operator_grants set permissions=array['claim_review'] where actor_id='d1000000-0000-4000-8000-000000000003';
set local role authenticated;
select extensions.throws_ok($$select public.get_listing_request_review((select id from f))$$,'P0001','review_forbidden','claim reviewer cannot publish listing');
reset role;
select * from extensions.finish();
rollback;
