begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into app.actors(id,workos_user_id,primary_email,email_verified,display_name) values
 ('a1000000-0000-4000-8000-000000000001','invite_owner','owner@fixture.example',true,'Fixture Owner'),
 ('a1000000-0000-4000-8000-000000000002','invite_coowner','coowner@fixture.example',true,'Fixture Co-owner'),
 ('a1000000-0000-4000-8000-000000000003','invite_manager','manager@fixture.example',false,'Fixture Manager'),
 ('a1000000-0000-4000-8000-000000000004','invite_operator','chussey@aia4.io',true,'Fixture Operator'),
 ('a1000000-0000-4000-8000-000000000005','invite_other','other@fixture.example',true,'Other');
insert into app.operator_grants(actor_id,allowlisted_email,permissions,status,approved_at,workos_organization_id) values('a1000000-0000-4000-8000-000000000004','chussey@aia4.io',array['claim_review'],'active',statement_timestamp(),'org_fixture');
insert into app.businesses(id,canonical_name) values('a2000000-0000-4000-8000-000000000001','Invitation Fixture');
insert into app.business_listings(id,business_id,current_slug,display_name,city_slug,postal_code,publication_status,published_at,owner_verified_at) values('a3000000-0000-4000-8000-000000000001','a2000000-0000-4000-8000-000000000001','invite-fixture','Invitation Fixture','reno','89502','published',statement_timestamp(),statement_timestamp());
insert into app.listing_participations(id,actor_id,listing_id,role,status,authority_scope,starts_at,expires_at) values('a4000000-0000-4000-8000-000000000001','a1000000-0000-4000-8000-000000000001','a3000000-0000-4000-8000-000000000001','business_owner','active','{"participants":"manage","listing_identity":"propose"}',statement_timestamp(),statement_timestamp()+interval '7 days');
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint-1000)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','manager@fixture.example','listing_manager',repeat('a',64),'fixture-invite-manager')$$,'P0001','reauth_required','stale owner cannot delegate');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','manager@fixture.example','listing_manager',repeat('a',64),'fixture-invite-manager')->>'idempotent','false','owner creates scoped invitation');
select extensions.is(public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','manager@fixture.example','listing_manager',repeat('a',64),'fixture-invite-manager')->>'idempotent','true','invitation duplicate click retains scope');
select extensions.throws_ok($$select public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','manager@fixture.example','business_owner',repeat('a',64),'fixture-invite-manager')$$,'P0001','idempotency_conflict','invitation replay cannot become owner');
reset role;
select extensions.is((select count(*)::integer from app.listing_participations where listing_id='a3000000-0000-4000-8000-000000000001'),1,'invitation itself creates no participation');
select extensions.ok(not has_table_privilege('authenticated','private.listing_invitations','select'),'invitation tokens and recipients are private');
select extensions.is((select token_hash from private.listing_invitations where idempotency_key='fixture-invite-manager'),encode(extensions.digest(repeat('a',64),'sha256'),'hex'),'stored invitation token is hashed');
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_other','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.accept_listing_invitation(repeat('a',64))$$,'P0001','invitation_identity_mismatch','wrong claimant cannot accept');
select extensions.throws_ok($$select public.get_listing_invitation(repeat('a',64))$$,'P0001','invitation_identity_mismatch','wrong claimant cannot inspect private invitation');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_manager','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.accept_listing_invitation(repeat('a',64))$$,'P0001','invitation_identity_mismatch','unverified email cannot accept');
reset role;
update app.actors set email_verified=true where workos_user_id='invite_manager';
set local role authenticated;
select extensions.is(public.get_listing_invitation(repeat('a',64))->>'name','Invitation Fixture','recipient can verify exact business before acceptance');
select extensions.is(public.get_listing_invitation(repeat('a',64))->>'role','listing_manager','recipient can verify exact role before acceptance');
select extensions.is(public.accept_listing_invitation(repeat('a',64))->>'role','listing_manager','recipient receives manager role');
select extensions.is(public.accept_listing_invitation(repeat('a',64))->>'idempotent','true','acceptance replay does not duplicate grant');
select extensions.throws_ok($$select public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','other@fixture.example','business_owner',repeat('e',64),'manager-overgrant-key')$$,'P0001','people_management_forbidden','manager cannot delegate owner role');
select extensions.throws_ok($$select public.get_listing_people('a3000000-0000-4000-8000-000000000001')$$,'P0001','people_management_forbidden','manager cannot access participant management');
reset role;
select extensions.is((select expires_at from app.listing_participations where actor_id='a1000000-0000-4000-8000-000000000003'),(select expires_at from app.listing_participations where id='a4000000-0000-4000-8000-000000000001'),'delegated grant expires with source owner');
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','coowner@fixture.example','business_owner',repeat('b',64),'fixture-invite-owner')->>'idempotent','false','owner invitation is explicitly owner-scoped');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_coowner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.accept_listing_invitation(repeat('b',64))->>'role','business_owner','second owner accepts bound invitation');
select extensions.throws_ok($$select public.revoke_listing_authority('a4000000-0000-4000-8000-000000000001','Revoke delegating owner')$$,'P0001','last_owner_protected','co-owner cannot cascade away both owners');
select extensions.is(public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','owner@fixture.example','listing_manager',repeat('c',64),'fixture-owner-manager')->>'idempotent','false','multiple roles may be invited separately');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.accept_listing_invitation(repeat('c',64))->>'role','listing_manager','owner can also have separate manager participation');
select extensions.is(public.revoke_listing_authority((select id from app.listing_participations where actor_id='a1000000-0000-4000-8000-000000000001' and role='listing_manager'),'Only manager role withdrawn')->>'status','revoked','specific manager role can be revoked');
reset role;
select extensions.is((select status from app.listing_participations where actor_id='a1000000-0000-4000-8000-000000000002' and role='business_owner'),'active','revoking manager does not revoke delegations from owner role');
select extensions.is((select status from app.listing_participations where actor_id='a1000000-0000-4000-8000-000000000003' and role='listing_manager'),'active','unrelated manager grant stays active');
set local role authenticated;
select extensions.is(public.create_listing_invitation('a3000000-0000-4000-8000-000000000001','other@fixture.example','listing_manager',repeat('d',64),'fixture-unused-manager')->>'idempotent','false','unused invitation created');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_operator','org_id','org_fixture','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.revoke_listing_authority('a4000000-0000-4000-8000-000000000001','Owner authority independently revoked')->>'status','revoked','operator can revoke whole source authority');
reset role;
select extensions.is((select count(*)::integer from app.listing_participations where listing_id='a3000000-0000-4000-8000-000000000001' and status='active'),0,'operator source revocation cascades accepted delegations');
select extensions.ok((select revoked_at is not null from private.listing_invitations where idempotency_key='fixture-unused-manager'),'source revocation invalidates unused invitations');
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_manager','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.accept_listing_invitation(repeat('a',64))$$,'P0001','invitation_unavailable','consumed invitation cannot reactivate revoked participation');
reset role;
-- Regranting the same person under a different authority cannot resurrect an old link.
insert into app.listing_participations(actor_id,listing_id,role,status,authority_scope,starts_at) values('a1000000-0000-4000-8000-000000000001','a3000000-0000-4000-8000-000000000001','business_owner','active','{"participants":"manage"}',statement_timestamp());
update private.listing_invitations set revoked_at=null where idempotency_key='fixture-unused-manager';
select set_config('request.jwt.claims',jsonb_build_object('sub','invite_other','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.accept_listing_invitation(repeat('d',64))$$,'P0001','invitation_unavailable','old delegation cannot bind to later owner grant');
reset role;
update private.listing_invitations set expires_at=statement_timestamp()-interval '1 second' where idempotency_key='fixture-unused-manager';
set local role authenticated;
select extensions.throws_ok($$select public.accept_listing_invitation(repeat('d',64))$$,'P0001','invitation_unavailable','expired invitation cannot accept');
reset role;
select set_config('request.jwt.claims','{"sub":"invite_owner","act":{"sub":"other"}}',true);
set local role authenticated;
select extensions.is(app.current_actor_id(),null::uuid,'impersonation supplies no business authority');
select * from extensions.finish();
rollback;
