begin;
create extension if not exists pgtap with schema extensions;
select extensions.plan(23);
insert into app.actors(id,workos_user_id,primary_email) values
('d1000000-0000-4000-8000-000000000001','profile_user_a','a@fixture.example'),
('d1000000-0000-4000-8000-000000000002','profile_user_b','b@fixture.example');
select extensions.ok(not has_function_privilege('anon','public.get_my_profile()','execute'),'anonymous cannot read profiles');
select extensions.ok(not has_function_privilege('anon','public.save_my_profile(jsonb,integer,text)','execute'),'anonymous cannot save profiles');
select extensions.ok(not has_table_privilege('authenticated','app.person_profiles','insert'),'no direct inserts');
select extensions.ok(not has_table_privilege('authenticated','app.person_profiles','update'),'no direct updates');
select set_config('request.jwt.claims','{"sub":"profile_user_a"}',true);
set local role authenticated;
select extensions.is(public.get_my_profile(),null::jsonb,'new user has no profile');
select extensions.is(public.save_my_profile('{"displayName":"Neighbor A","city":"reno","bio":"Synthetic introduction."}',0,'profile-save-a')->>'version','1','new profile saved');
select extensions.is(public.save_my_profile('{"displayName":"Neighbor A","city":"reno","bio":"Synthetic introduction."}',0,'profile-save-a')->>'version','1','response loss replay does not duplicate');
select extensions.is(public.get_my_profile()->>'displayName','Neighbor A','saved profile read back');
select extensions.throws_ok($$select public.save_my_profile('{"displayName":"Changed","city":"reno","bio":""}',0,'profile-save-a')$$,'P0001','idempotency_conflict','same key changed payload refused');
select extensions.throws_ok($$select public.save_my_profile('{"displayName":"Changed","city":"reno","bio":""}',0,'profile-stale-a')$$,'P0001','profile_changed','stale writer refused');
select extensions.throws_ok($$select public.save_my_profile('{"displayName":"Neighbor A","city":"reno","bio":"","role":"business_owner"}',1,'profile-forge-a')$$,'P0001','invalid_profile','forged authority refused');
select extensions.throws_ok($$select public.save_my_profile('{"displayName":"Neighbor A","city":"reno","bio":"","actorId":"d1000000-0000-4000-8000-000000000002"}',1,'profile-forge-b')$$,'P0001','invalid_profile','forged target refused');
select extensions.throws_ok($$select public.save_my_profile('{"displayName":" ","city":"reno","bio":""}',1,'profile-invalid-a')$$,'P0001','invalid_profile','empty name refused');
select extensions.throws_ok($$select public.save_my_profile(jsonb_build_object('displayName',U&'\00A0\00A0','city','reno','bio',''),1,'profile-space-a')$$,'P0001','invalid_profile','Unicode whitespace-only name refused at RPC');
select extensions.is(public.save_my_profile('{"displayName":"Updated Neighbor","city":"","bio":""}',1,'profile-edit-a')->>'version','2','optional fields can be cleared');
reset role;
select extensions.is((select count(*)::integer from app.audit_events where action='person_profile.saved'),2,'exactly one audit per accepted change');
select extensions.ok(not exists(select 1 from app.audit_events where action='person_profile.saved' and after_ref ? 'bio'),'audit excludes personal content');
select extensions.is((select count(*)::integer from app.listing_participations where actor_id='d1000000-0000-4000-8000-000000000001'),0,'profile grants no business authority');
select set_config('request.jwt.claims','{"sub":"profile_user_b"}',true);
set local role authenticated;
select extensions.is((select count(*)::integer from app.person_profiles),0,'cross-user rows hidden by RLS');
select extensions.is(public.get_my_profile(),null::jsonb,'second user cannot query first profile');
select extensions.is(public.save_my_profile('{"displayName":"Neighbor B","city":"sparks","bio":""}',0,'profile-save-a')->>'displayName','Neighbor B','keys are isolated by actor');
reset role;
select set_config('request.jwt.claims','{"sub":"profile_user_a"}',true);
set local role authenticated;
select extensions.is(public.get_my_profile()->>'displayName','Updated Neighbor','refresh/relogin returns persisted own profile');
reset role;
update app.actors set status='suspended' where workos_user_id='profile_user_a';
set local role authenticated;
select extensions.throws_ok($$select public.get_my_profile()$$,'P0001','authentication_required','suspended actor loses profile access');
reset role;
select * from extensions.finish();
rollback;
