begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into app.actors(id,workos_user_id,primary_email) values
('c1000000-0000-4000-8000-000000000001','file_owner','owner@fixture.example'),
('c1000000-0000-4000-8000-000000000002','file_other','other@fixture.example'),
('c1000000-0000-4000-8000-000000000003','file_operator','chussey@aia4.io');
insert into app.operator_grants(actor_id,allowlisted_email,permissions,status,approved_at,workos_organization_id) values('c1000000-0000-4000-8000-000000000003','chussey@aia4.io',array['claim_review'],'active',statement_timestamp(),'org_file');
insert into app.businesses(id,canonical_name) values('c2000000-0000-4000-8000-000000000001','File Fixture');
insert into app.business_listings(id,business_id,current_slug,display_name,city_slug,postal_code,publication_status,published_at) values('c3000000-0000-4000-8000-000000000001','c2000000-0000-4000-8000-000000000001','file-fixture','File Fixture','reno','89502','published',statement_timestamp());
select set_config('request.jwt.claims',jsonb_build_object('sub','file_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select public.submit_listing_claim('c3000000-0000-4000-8000-000000000001','document','file-submit-key','listing_manager');
reset role;
create temporary table f as select id claim_id,evidence_challenge challenge,null::uuid proof_id,null::uuid lease from app.claims where submission_idempotency_key='file-submit-key';
grant select,update on f to authenticated,service_role;
set local role authenticated;
update f set proof_id=(public.reserve_synthetic_claim_proof(claim_id,challenge,repeat('a',64),64,'application/pdf','Synthetic exact manager authority fixture.','file-reserve-key')->>'id')::uuid;
select extensions.is(public.reserve_synthetic_claim_proof((select claim_id from f),(select challenge from f),repeat('a',64),64,'application/pdf','Synthetic exact manager authority fixture.','file-reserve-key')->>'idempotent','true','retry binds original claim/challenge/bytes');
select extensions.throws_ok($$select public.reserve_synthetic_claim_proof((select claim_id from f),(select challenge from f),repeat('b',64),64,'application/pdf','Synthetic exact manager authority fixture.','file-reserve-key')$$,'P0001','idempotency_conflict','replacement bytes rejected');
select extensions.throws_ok($$select public.reserve_synthetic_claim_proof((select claim_id from f),(select challenge from f),repeat('a',64),64,'application/pdf','Synthetic exact manager authority fixture.','file-replay-key')$$,'P0001','challenge_expired_or_replayed','challenge single use across files');
select extensions.throws_ok($$select public.authorize_synthetic_claim_proof_download((select proof_id from f))$$,'P0001','proof_unavailable','quarantine inaccessible');
select extensions.is(jsonb_array_length(public.get_my_claim_file_status((select claim_id from f))),1,'own status visible without object key');
select extensions.ok(not (public.get_my_claim_file_status((select claim_id from f))->0)?'path','object keys excluded from claimant metadata');
reset role;
select extensions.ok(not has_table_privilege('authenticated','private.claim_file_jobs','select'),'private proof table denied');
select extensions.ok(not has_function_privilege('authenticated','public.finish_synthetic_claim_proof(uuid,uuid,jsonb)','execute'),'claimant cannot forge scan receipt');
select extensions.ok(not has_function_privilege('authenticated','public.lease_synthetic_proof_deletions()','execute'),'claimant cannot lease deletion');
select set_config('request.jwt.claims','{"sub":"file_other"}',true);
set local role authenticated;
select extensions.throws_ok($$select public.get_my_claim_file_status((select claim_id from f))$$,'P0001','claim_access_forbidden','other claimant isolated');
reset role;
update f set lease=(public.acquire_synthetic_claim_proof(proof_id)->>'lease')::uuid;
select extensions.throws_ok($$select public.acquire_synthetic_claim_proof((select proof_id from f))$$,'P0001','proof_processing_busy','only one worker lease');
select extensions.throws_ok($$select public.finish_synthetic_claim_proof((select proof_id from f),extensions.gen_random_uuid(),'{"status":"synthetic_clean"}')$$,'P0001','proof_lease_expired','wrong lease cannot finalize');
select extensions.throws_ok($$select public.finish_synthetic_claim_proof((select proof_id from f),(select lease from f),jsonb_build_object('status','synthetic_clean','sha256',repeat('b',64),'engine','fixture','version','1','signaturesAt',statement_timestamp(),'decoded',jsonb_build_object('pages',1)))$$,'P0001','invalid_scan_receipt','scan hash must match reserved bytes');
select extensions.throws_ok($$select public.finish_synthetic_claim_proof((select proof_id from f),(select lease from f),jsonb_build_object('status','synthetic_clean','sha256',repeat('a',64),'engine','fixture','version','1','signaturesAt',statement_timestamp(),'decoded',jsonb_build_object('pages',21)))$$,'P0001','invalid_scan_receipt','twenty PDF page limit enforced in worker RPC');
select extensions.throws_ok($$select public.finish_synthetic_claim_proof((select proof_id from f),(select lease from f),jsonb_build_object('status','synthetic_clean','sha256',repeat('a',64),'engine','fixture','version','1','signaturesAt',statement_timestamp(),'decoded',jsonb_build_object('pages','1')))$$,'P0001','invalid_scan_receipt','decoded page count must be numeric');
select extensions.is(public.finish_synthetic_claim_proof((select proof_id from f),(select lease from f),jsonb_build_object('status','synthetic_clean','sha256',repeat('a',64),'engine','fixture','version','1','signaturesAt',statement_timestamp(),'decoded',jsonb_build_object('pages',1)))->>'status','synthetic_clean','clean fixture is explicitly synthetic');
select extensions.throws_ok($$select public.finish_synthetic_claim_proof((select proof_id from f),(select lease from f),'{"status":"unavailable"}')$$,'P0001','proof_lease_expired','completed lease cannot replay');
select extensions.is((select count(*)::integer from private.claim_evidence where claim_id=(select claim_id from f)),0,'synthetic file creates no authority evidence');
select set_config('request.jwt.claims',jsonb_build_object('sub','file_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint-1000)::text,true);
set local role authenticated;
select extensions.throws_ok($$select public.authorize_synthetic_claim_proof_download((select proof_id from f))$$,'P0001','reauth_required','own private download requires recent auth');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','file_owner','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.authorize_synthetic_claim_proof_download((select proof_id from f))->>'mode','synthetic','own synthetic download authorized and audited');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','file_operator','org_id','org_file','auth_time',floor(extract(epoch from statement_timestamp()))::bigint)::text,true);
set local role authenticated;
select extensions.is(public.authorize_synthetic_claim_proof_download((select proof_id from f))->>'mode','synthetic','recent reviewer can access synthetic file');
select extensions.throws_ok($$select public.decide_listing_claim((select claim_id from f),'approved','Synthetic scan alone is not authority','file-approve-key')$$,'P0001','independent_authority_review_required','synthetic clean never grants authority');
select public.decide_listing_claim((select claim_id from f),'rejected','Synthetic request rejected for independent review','file-reject-key');
reset role;
select extensions.ok((select delete_after=(select decided_at from app.claims where id=claim_id)+interval '30 days' from private.claim_file_jobs where id=(select proof_id from f)),'rejected decision schedules thirty day proof retention');
select extensions.is(jsonb_array_length(public.lease_synthetic_proof_deletions()),0,'cannot delete before retention deadline');
update private.claim_file_jobs set delete_after=statement_timestamp()-interval '1 second' where id=(select proof_id from f);
update f set lease=(public.lease_synthetic_proof_deletions()->0->>'lease')::uuid;
select extensions.is(jsonb_array_length(public.lease_synthetic_proof_deletions()),0,'active deletion lease cannot double claim');
select extensions.throws_ok($$select public.confirm_synthetic_proof_deleted((select proof_id from f),extensions.gen_random_uuid())$$,'P0001','proof_lease_expired','wrong deletion lease rejected');
select extensions.ok(public.confirm_synthetic_proof_deleted((select proof_id from f),(select lease from f)),'worker deletion receipt accepted after explicit lease');
select extensions.ok(public.confirm_synthetic_proof_deleted((select proof_id from f),(select lease from f)),'object absence/replay idempotent');
select extensions.ok((select explanation is null and sha256=repeat('a',64) and scan_receipt is not null and deleted_at is not null from private.claim_file_jobs where id=(select proof_id from f)),'private narrative redacted; hash/scan metadata retained');
set local role authenticated;
select extensions.throws_ok($$select public.authorize_synthetic_claim_proof_download((select proof_id from f))$$,'P0001','proof_unavailable','deleted proof inaccessible');
reset role;
select extensions.is((select count(*)::integer from app.audit_events where action='claim.synthetic_proof_deleted'),1,'one durable deletion receipt');
select * from extensions.finish();
rollback;
