/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as ListYourBusinessRouteImport } from './routes/list-your-business'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BizSlugRouteImport } from './routes/biz.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as NvCityRouteImport } from './routes/nv.$city'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NvCityCategoryRouteImport } from './routes/nv.$city.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourBusinessRoute = ListYourBusinessRouteImport.update({
  id: '/list-your-business',
  path: '/list-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BizSlugRoute = BizSlugRouteImport.update({
  id: '/biz/$slug',
  path: '/biz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const NvCityRoute = NvCityRouteImport.update({
  id: '/nv/$city',
  path: '/nv/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/studio/$slug',
  path: '/studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NvCityCategoryRoute = NvCityCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => NvCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cities': typeof CitiesRoute
  '/claim': typeof ClaimRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/spec': typeof SpecRoute
  '/terms': typeof TermsRoute
  '/biz/$slug': typeof BizSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/nv/$city': typeof NvCityRouteWithChildren
  '/studio/$slug': typeof StudioSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nv/$city/$category': typeof NvCityCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cities': typeof CitiesRoute
  '/claim': typeof ClaimRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/spec': typeof SpecRoute
  '/terms': typeof TermsRoute
  '/biz/$slug': typeof BizSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/nv/$city': typeof NvCityRouteWithChildren
  '/studio/$slug': typeof StudioSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nv/$city/$category': typeof NvCityCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/cities': typeof CitiesRoute
  '/claim': typeof ClaimRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/spec': typeof SpecRoute
  '/terms': typeof TermsRoute
  '/biz/$slug': typeof BizSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/nv/$city': typeof NvCityRouteWithChildren
  '/studio/$slug': typeof StudioSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nv/$city/$category': typeof NvCityCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/categories'
    | '/cities'
    | '/claim'
    | '/list-your-business'
    | '/login'
    | '/offers'
    | '/privacy'
    | '/register'
    | '/search'
    | '/spec'
    | '/terms'
    | '/biz/$slug'
    | '/categories/$slug'
    | '/nv/$city'
    | '/studio/$slug'
    | '/api/auth/$'
    | '/nv/$city/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/categories'
    | '/cities'
    | '/claim'
    | '/list-your-business'
    | '/login'
    | '/offers'
    | '/privacy'
    | '/register'
    | '/search'
    | '/spec'
    | '/terms'
    | '/biz/$slug'
    | '/categories/$slug'
    | '/nv/$city'
    | '/studio/$slug'
    | '/api/auth/$'
    | '/nv/$city/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/categories'
    | '/cities'
    | '/claim'
    | '/list-your-business'
    | '/login'
    | '/offers'
    | '/privacy'
    | '/register'
    | '/search'
    | '/spec'
    | '/terms'
    | '/biz/$slug'
    | '/categories/$slug'
    | '/nv/$city'
    | '/studio/$slug'
    | '/api/auth/$'
    | '/nv/$city/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CitiesRoute: typeof CitiesRoute
  ClaimRoute: typeof ClaimRoute
  ListYourBusinessRoute: typeof ListYourBusinessRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SpecRoute: typeof SpecRoute
  TermsRoute: typeof TermsRoute
  BizSlugRoute: typeof BizSlugRoute
  NvCityRoute: typeof NvCityRouteWithChildren
  StudioSlugRoute: typeof StudioSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-business': {
      id: '/list-your-business'
      path: '/list-your-business'
      fullPath: '/list-your-business'
      preLoaderRoute: typeof ListYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz/$slug': {
      id: '/biz/$slug'
      path: '/biz/$slug'
      fullPath: '/biz/$slug'
      preLoaderRoute: typeof BizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/nv/$city': {
      id: '/nv/$city'
      path: '/nv/$city'
      fullPath: '/nv/$city'
      preLoaderRoute: typeof NvCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/studio/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nv/$city/$category': {
      id: '/nv/$city/$category'
      path: '/$category'
      fullPath: '/nv/$city/$category'
      preLoaderRoute: typeof NvCityCategoryRouteImport
      parentRoute: typeof NvCityRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface NvCityRouteChildren {
  NvCityCategoryRoute: typeof NvCityCategoryRoute
}

const NvCityRouteChildren: NvCityRouteChildren = {
  NvCityCategoryRoute: NvCityCategoryRoute,
}

const NvCityRouteWithChildren =
  NvCityRoute._addFileChildren(NvCityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  CitiesRoute: CitiesRoute,
  ClaimRoute: ClaimRoute,
  ListYourBusinessRoute: ListYourBusinessRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SpecRoute: SpecRoute,
  TermsRoute: TermsRoute,
  BizSlugRoute: BizSlugRoute,
  NvCityRoute: NvCityRouteWithChildren,
  StudioSlugRoute: StudioSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
